### ISSUE TITLE
猫毅

### ISSUE THREAD

**Issue by cats-food** [tjuxiaoyi/changeDesktopFromBing#1]

**Comment by tjuxiaoyi** [comment]
there is no bug in my code！
don't give me issue.

**Comment by cats-food** [comment]
YOU!! YOU are the real problem!
you are doing dirty works for Evan Quartz  and his machine Cliffy!

**Comment by tjuxiaoyi** [comment]
你! !你才是真正的问题!
你在为埃文·石英和他的机器干脏活克里夫!













At 2021-03-19 13:41:59, "catFood" ***@***.***> wrote:

YOU!! YOU are the real problem!
you are doing dirty works for Evan Quartz and his machine Cliffy!
